# Created: January 2019
# TUTORIAL: Check if pecan is a nut from the food taxonomy from the SmartProducts project http://projects.kmi.open.ac.uk/smartproducts/ontology.html
# Creator: Amelie Gyrard, Knoesis, Wright State University (WSU), Ohio, USA

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX food_taxonomy: <http://kmi.open.ac.uk/projects/smartproducts/ontologies/food_taxonomy.owl>

ASK WHERE{
	?foodURI rdfs:subClassOf ?foodParentURI.
	#?nutURI rdfs:label ?nutLabel.
}

# RDF example:
#    <!-- http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#ButternutSquash -->
#
#    <owl:Class rdf:about="http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#ButternutSquash">
#        <rdfs:label>Butternut Squash</rdfs:label>
#       <rdfs:subClassOf rdf:resource="http://kmi.open.ac.uk/projects/smartproducts/ontologies/food.owl#WinterSquash"/>
#    </owl:Class>