# Created: November 2018
# TUTORIAL: Query the patient's age
# Creator: Amelie Gyrard, Knoesis, Wright State University (WSU), Ohio, USA

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 

SELECT DISTINCT ?patientURI ?patientLabel ?patientComment ?age  WHERE{
	?patientURI rdfs:label ?patientLabel.
	?patientURI rdfs:comment ?patientComment.
	?patientURI foaf:age ?age. 	
}

# RDF example:
# 	<owl:NamedIndividual rdf:about="Patient_id_KH030">		
#		<rdfs:label xml:lang="en">Patient id number KH030</rdfs:label>
#		<rdfs:comment xml:lang="en">Patient id number KH030</rdfs:comment>
#		<rdf:type rdf:resource="https://schema.org/Person"/>
#		<foaf:age rdf:datatype="http://www.w3.org/2001/XMLSchema#integer">13.0</foaf:age>
#		<kao:hasSymptom rdf:resource="http://purl.org/kao#CannotTalkInFullSentence"/>
#	</owl:NamedIndividual>