# TUTORIAL: Get more information about medication (e.g. ventolin) from the drug ontology rxnorm
# Creator: Amelie Gyrard, Knoesis, Wright State University (WSU), Ohio, USA
# Created: November 2018

DESCRIBE ?drugOntologyRxnormMedicationURI

