# Created: November 2018
# TUTORIAL: Query the patient's symptom
# Creator: Amelie Gyrard, Knoesis, Wright State University (WSU), Ohio, USA

PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX kao: <http://purl.org/kao#>

SELECT DISTINCT ?patientURI ?patientLabel ?patientComment ?symptomLabel ?symptomURI ?symptomURIrequested WHERE{
	?patientURI rdfs:label ?patientLabel.
	?patientURI rdfs:comment ?patientComment.
	?patientURI kao:hasSymptom ?symptomURI. 
	?symptomURI rdfs:label ?symptomLabel.
	
	FILTER ( ?symptomURI = ?symptomURIrequested)
}

# RDF example:
# 	<owl:NamedIndividual rdf:about="Patient_id_KH030">		
#		<rdfs:label xml:lang="en">Patient id number KH030</rdfs:label>
#		<rdfs:comment xml:lang="en">Patient id number KH030</rdfs:comment>
#		<rdf:type rdf:resource="https://schema.org/Person"/>
#		<kao:hasSymptom rdf:resource="http://purl.org/kao#CannotTalkInFullSentence"/>
#	</owl:NamedIndividual>