# Created: November 2018
# Query patients and their symptoms

PREFIX kao: <http://purl.org/kao#>
PREFIX schema: <https://schema.org/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?patientURI ?patientLabel ?patientComment ?symptom ?symptomLabel ?riskFactorLabel ?therapyURI ?therapyLabel ?therapyComment ?age ?therapyLinkedOpenDataLabel ?therapyLinkedOpenDataURI WHERE{
	?patientURI rdfs:label ?patientLabel.
	?patientURI rdfs:comment ?patientComment.
	
	?patientURI foaf:age ?age. 
	
	?patientURI kao:hasTherapy ?therapyURI.
	?therapyURI rdfs:comment ?therapyComment. 
	?therapyURI rdfs:label ?therapyLabel. 
		 
	?patientURI kao:hasSymptom ?symptom. 	 
	?symptom rdfs:label ?symptomLabel.
	
	?patientURI kao:hasRiskFactor ?riskFactorURI. 
	?riskFactorURI rdfs:label ?riskFactorLabel.
	 
	
	#?patientURI rdf:type schema:Patient.
	
	#FILTER (LANGMATCHES(LANG(?therapyLabel), "en")).
	
	OPTIONAL{ # Ventolin Scenario - rdfs:seelAlso - Linked Open Data
	?therapyURI rdfs:seeAlso ?therapyLinkedOpenDataURI.
	?therapyLinkedOpenDataURI rdfs:label ?therapyLinkedOpenDataLabel.
	
	}
	
}