# Created: February 2019
# TUTORIAL: Get the more information about chest sound, cough, etc.
# Creator: Amelie Gyrard, Knoesis, Wright State University (WSU), Ohio, USA

PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> 

SELECT DISTINCT ?potentialSymptom ?label WHERE{
	?potentialSymptom rdfs:label ?label.
	FILTER ( xsd:string("dry cough") = ?label). # works only if exact match
	
	#FILTER (LANGMATCHES(LANG(?label), "en")). # can be used only if labels are explicitly mentioned that they will be in English
}

#    <owl:Class rdf:about="http://purl.obolibrary.org/obo/SYMP_0000025">
#        <rdfs:subClassOf rdf:resource="http://purl.obolibrary.org/obo/SYMP_0000614"/>
#        <oboInOwl:hasOBONamespace rdf:datatype="http://www.w3.org/2001/XMLSchema#string">symptoms</oboInOwl:hasOBONamespace>
#        <oboInOwl:id rdf:datatype="http://www.w3.org/2001/XMLSchema#string">SYMP:0000025</oboInOwl:id>
#        <rdfs:label rdf:datatype="http://www.w3.org/2001/XMLSchema#string">dry cough</rdfs:label>
#    </owl:Class>
