# TUTORIAL: Query the patient's Body Mass Index (BMI) after executing the inference engine
# Creator: Amelie Gyrard, Knoesis, Wright State University (WSU), Ohio, USA
# Created: December 2018:


PREFIX kao: <http://purl.org/kao#>
PREFIX sosa: <http://www.w3.org/ns/sosa/>
PREFIX qudt: <http://qudt.org/schema/qudt#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX dc: <http://purl.org/dc/elements/1.1/>

SELECT DISTINCT ?bodyMassIndex WHERE{
		?patient kao:hasBodyMassIndex ?bodyMassIndex # scenario Body Mass Index (BMI) - Obesity
}